### ISSUE TITLE
enhancement

### ISSUE THREAD

**Issue by jeanpierrerossi** [nschiett/fishualize#10]
Serranus scriba (fam. Serranidae) is a nice benthic fish very common in Mediterranean Sea and present in the western Atlantic and black sea as well. In Corsica, we call it “barchetta”. Its English name is “painted comber”.

#65071c
#b90b0a
#ef0d00
#72ccfe
#3d63a0

**Comment by nschiett** [comment]
excellent, thanks! the species will be added in version 2.0
