### ISSUE TITLE
ENHANCEMENT

### ISSUE THREAD

**Issue by jdittrich** [nschiett/fishualize#11]
Forcipiger_longirostris
#e3b01d
#fefb29
#bbd84e
#afe8fc
#696c8f

![image](https://user-images.githubusercontent.com/3416487/77956151-b0503800-72d1-11ea-8212-5f9e2aa588eb.png)

**Comment by nschiett** [comment]
Thanks for the contribution, it's a great palette! 
Will be available soon in fishualize 2.0!
