### ISSUE TITLE
Missing species

### ISSUE THREAD

**Issue by GreenLe** [nschiett/fishualize#18]
A-M-A-Z-I-N-G package. I love it all (especially the O. longirostris colour palette). Working with an invasive species of Eurasian goby, I'd love to see it included, not only as a palette, but also as an icon. Since I do all my work in R and have a few manuscripts in the pipeline, I can see a lot of usage (and a few citations coming up). 
It is...

Neogobius melanostomus

It has amazing colours, a matted latte base, with some darker shades, and brown-black dominant males. There's a hint of light blue around a pigmented eye-spot on the first dorsal fin, and the fin trims have this light pale fluorescence. You'll see once you start looking at pictures. 

Representative pictures: 
https://b8i7g4g7.stackpathcdn.com/wp-content/uploads/2015/09/Neogobius-melanostomus-Round-Goby.jpg
https://c8.alamy.com/comp/2B1524P/round-goby-neogobius-melanostomus-swimming-male-side-view-2B1524P.jpg
https://lh3.googleusercontent.com/proxy/Pe1bhvhsBjycFKHsK2d7tP-v2XVD-cL7uZz8U25x6QOe9xWTWzg0uj5-SvBQ8rMp-F_DtQSAqh5wHOGWdQAMtS1NTkCPUEmu9YM
https://lh3.googleusercontent.com/proxy/Mply66aC9vJJwjTtrclZrivJzkFGrVbNKQxcuodIky6oaDXTxxM87E3J5A9xUMqB0rbrmjgVVubigoM0Gd7I6vQy-yjkaKsa34oVnUxcPfdwngL1

Thank you for a great package and your love for the beauty of the natural world!

Cheers,
Leon

**Comment by nschiett** [comment]
Hi Leon, 
Thanks for the nice message and your enthusiasm. With some delay, I added a palette. You can access it through the github version. 
Cheers!
