### ISSUE TITLE
I can't get it to work anymore...

### ISSUE THREAD

**Issue by amedellin** [nschiett/fishualize#28]
I updated R and Studio, reinstalled grom github and keep getting this message when trying to upload a fishape():

> ggplot(diamonds)+
+     geom_bar(aes(cut, fill = cut)) +
+     scale_fill_fish_d(option = "Naso_lituratus") +
+     add_fishape(family = "Acanthuridae",
+                 option = "Naso_unicornis",
+                 xmin = 1, xmax = 3, ymin = 15000, ymax = 20000,
+                 fill = fish(option = "Naso_lituratus", n = 5)[3],
+                 alpha = 0.8) +
+     theme_bw()
Error in add_fishape(family = "Acanthuridae", option = "Naso_unicornis",  : 
  This family is not available or misspelled
In addition: Warning message:
Expected 2 pieces. Additional pieces discarded in 1 rows [1]. 

Do you have any idea what's happening? 
Thanks in advance!

**Comment by brendanford24** [comment]
Seems like the `fishapes` functions is broken.  The shapes are on GitHub. The GitHub page for the folder of fish shapes is parsed by `fishapes` and all available family and species names are returned in a data frame. However it seems like the webpage is no longer parsed correctly (at least on our machines). Note that `add_fishape` calls `fishapes` which is was it is also broken.

**Comment by LauraMannocci** [comment]
Hi @nschiett, we are having the same issue with add_fishape
Do you have any temporary fix that would allow us to continue working with add_fishape ?

Many thanks
