### ISSUE TITLE
Common names

### ISSUE THREAD

**Issue by jlacko** [nschiett/fishualize#3]
Dear maintainers,
would you consider a pull request implementing common names as synonyms to the scientific names?
Say recognizing both "mahi-mahi" and "dorado" as a synonyms of the right & proper "Coryphaena_hippurus", which however does not exactly roll of the tongue ?
Easily done from technical perspective and might make the package more accessible to a wider audience.
Speaking of which, are you looking for help with cleaning up the notes on build? These might be a problem for a CRAN release, which you definitely should be aiming for! :)
J.

**Comment by nschiett** [comment]
Hi! Thanks for your suggestion!
I definitely see your point and we have thought about including common names. Ultimately, we decided to stick with scientific names as they are universal across all languages. Also, even in the same language there might be multiple options for common names. A synonym for "mahi-mahi" for example would be "common dolphinfish". I agree that most Latin names don't exactly roll of the tongue but in the end it may be easier just to stick with the standardized scientific nomenclature. 
We definitely want to submit to CRAN (notes are fixed now). Thanks for the support :). We might add some extra palettes, but probably we'll submit by the end of the week.

**Comment by jlacko** [comment]
I get your point.

My suggestion of using common names as synonyms (i.e. in addition, not as replacement of scientific names) was based on the idea that synonyms allow many to one relationship, as shown here:

```r 
nput <- "chat"

translation <- c("cat" = "felis", "chat" = "felis", "gato" = "felis", "dog" = "canis")

if(!is.na(translation[input])) input <- translation[input]

cat(input)
```
But it is your package, and your call to make :)

Best of luck with the submission!
