### ISSUE TITLE
package ‘fishualize’ is not available (for R version 3.4.3)

### ISSUE THREAD

**Issue by JavierEspinozaM** [nschiett/fishualize#5]
Hello everyone, 

I have a problem to install Fishualize in RStudio. The message is:

Warning in install.packages :
  package ‘fishualize’ is not available (for R version 3.4.3)

Thaks!

**Comment by nschiett** [comment]
fishualize is currently not on CRAN. It will be relatively soon. 
Until then, here's how you can install the package:
`install.packages("devtools")`
`library(devtools)`
`devtools::install_github("nschiett/fishualize", force = TRUE)`
`library(fishualize)`
Does that work for you?

**Comment by nschiett** [comment]
fishualize is on CRAN now.  `install.packages("fishualize")` will work.

**Comment by JavierEspinozaM** [comment]
Hello @nschiett !

it's working! Thanks!
