### ISSUE TITLE
Stethojulis_bandanensis

### ISSUE THREAD

**Issue by pomboal** [nschiett/fishualize#6]
#4 
Stethojulis_bandanensis
#00486dff
#8fcbbbff
#01e6e5ff
#fed449ff
#f84213ff

**Comment by nschiett** [comment]
Thanks! Love the palette, I added it to the package. 
For now, it'll only be available in the development version so you'll have to reinstall "fishualize" through `devtools::install_github("nschiett/fishualize", force = TRUE)` to use it.
